# Generated by Django 4.1.1 on 2023-02-28 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateskillsandtechnologies',
            name='profile_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app1.jobseekerprofile'),
        ),
    ]
