# Generated by Django 4.1.1 on 2023-01-31 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_jobseekerprofile_employeerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('JOBSEEKER', 'jobseeker'), ('EMPLOYEER', 'employeer'), ('MODERATOR', 'moderator')], max_length=50),
        ),
    ]
