# Generated by Django 4.1.1 on 2023-04-03 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_interviewscheduling_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interviewscheduling',
            old_name='interview_schuduling_id',
            new_name='interview_id',
        ),
    ]
