# Generated by Django 4.1.1 on 2023-01-09 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_employeer_jobseeker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobdetails',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=100)),
                ('job_description', models.CharField(max_length=500)),
                ('contact_email', models.CharField(max_length=100)),
                ('job_type', models.CharField(max_length=100)),
                ('specialisation', models.CharField(max_length=100)),
                ('experience', models.IntegerField(blank=True, null=True)),
                ('expected_salary', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('vacancies', models.IntegerField(blank=True, null=True)),
                ('lastdate', models.DateField()),
                ('cmp_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
