# Generated by Django 4.1.1 on 2023-02-15 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_jobdetails_cmp_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdetails',
            name='cmp_profile',
        ),
        migrations.AddField(
            model_name='jobdetails',
            name='cmp_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
