# Generated by Django 4.1.1 on 2023-01-09 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_jobdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='cmp_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app1.employeer'),
        ),
    ]
