# Generated by Django 4.1.1 on 2023-02-28 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_jobseekerprofile_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='state',
        ),
    ]
