# Generated by Django 4.1.1 on 2023-02-02 06:19

import app1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeerprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employeerprofile',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='static/emplyeer/logos/'),
        ),
        migrations.AddField(
            model_name='employeerprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeerprofile',
            name='office_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeerprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[app1.models.validate_phone_number]),
        ),
        migrations.AddField(
            model_name='employeerprofile',
            name='pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeerprofile',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
