# Generated by Django 4.1.1 on 2023-04-11 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_rename_interview_schuduling_id_interviewscheduling_interview_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverLetterDetails',
            fields=[
                ('coverletter_id', models.AutoField(primary_key=True, serialize=False)),
                ('coverlettertitle', models.CharField(blank=True, max_length=255, null=True)),
                ('coverletter', models.CharField(blank=True, max_length=30000, null=True)),
                ('profile', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app1.jobseekerprofile')),
            ],
        ),
    ]
