# Generated by Django 4.1.1 on 2023-02-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_employeerprofile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeerprofile',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
