# Generated by Django 4.1.1 on 2023-04-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_coverletterdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverletterdetails',
            name='coverletter',
            field=models.TextField(blank=True, max_length=30000, null=True),
        ),
    ]
