# Generated by Django 4.1.1 on 2023-02-20 04:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='emp_profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
