# Generated by Django 4.1.1 on 2023-03-05 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_jobapplicationdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplicationdetails',
            old_name='job_id',
            new_name='job',
        ),
    ]
