# Generated by Django 4.1.1 on 2023-02-08 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_employeerprofile_company_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeerprofile',
            name='employeer_id',
        ),
    ]
