# Generated by Django 4.1.1 on 2023-02-20 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_skills_emp_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='cmp_profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app1.employeerprofile'),
        ),
    ]
