# Generated by Django 4.1.1 on 2023-03-06 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_rename_job_id_jobapplicationdetails_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplicationdetails',
            name='employerprofile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app1.employeerprofile'),
        ),
        migrations.AlterField(
            model_name='jobapplicationdetails',
            name='applicant_resume',
            field=models.FileField(blank=True, null=True, upload_to='pdf/'),
        ),
    ]
