# Generated by Django 4.1.1 on 2023-04-12 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_interviewscheduling_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewscheduling',
            name='job',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.jobdetails'),
        ),
    ]
