# Generated by Django 4.1.1 on 2023-02-20 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_jobdetails_cmp_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdetails',
            name='cmp_profile',
        ),
    ]
