# Generated by Django 4.1.1 on 2023-03-07 03:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_jobapplicationdetails_employerprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplicationdetails',
            name='created_by',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
