# Generated by Django 4.1.1 on 2023-02-21 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_remove_jobdetails_cmp_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualifications',
            name='qualification_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='skills',
            name='skill_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
