# Generated by Django 4.1.1 on 2023-02-21 07:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_qualifications_qualification_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='publisheddate',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
