# Generated by Django 4.1.1 on 2023-03-07 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_jobapplicationdetails_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplicationdetails',
            old_name='created_by',
            new_name='created_at',
        ),
    ]
