# Generated by Django 4.1.1 on 2023-04-13 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_interviewscheduling_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewscheduling',
            name='message',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
