# Generated by Django 4.1.1 on 2023-03-07 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_rename_created_by_jobapplicationdetails_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplicationdetails',
            name='created_at',
        ),
    ]
