# Generated by Django 4.1.1 on 2023-02-24 07:14

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('app1', '0009_jobdetails_publisheddate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobseekerprofile',
            old_name='jobseeker_id',
            new_name='age',
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='highestqualification',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='languages',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
