# Generated by Django 4.1.1 on 2023-03-15 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
