# Generated by Django 4.1.1 on 2023-02-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_jobseekerprofile_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='aboutyourself',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
