# Generated by Django 4.1.1 on 2023-03-15 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeSchema',
            fields=[
                ('resume_id', models.AutoField(primary_key=True, serialize=False)),
                ('seekername', models.CharField(blank=True, max_length=100, null=True)),
                ('careerobjective', models.CharField(blank=True, max_length=500, null=True)),
                ('profilepicture', models.FileField(blank=True, null=True, upload_to='resumeprofile/')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phonenumber', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('skills', models.CharField(blank=True, max_length=200, null=True)),
                ('jprofile', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app1.jobseekerprofile')),
            ],
        ),
    ]
