# Generated by Django 4.1.1 on 2023-03-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_resumeschema_resumetitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeschema',
            name='projectdescription',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='resumeschema',
            name='projecttitle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
