# Generated by Django 4.1.1 on 2023-03-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_resumeschema_projectdescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeschema',
            name='collegename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resumeschema',
            name='coursename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resumeschema',
            name='passingyear',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
    ]
