# Generated by Django 4.1.1 on 2023-03-23 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_resumeschema_collegename_resumeschema_coursename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeschema',
            name='passingyear',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
