# Generated by Django 4.1.1 on 2023-03-23 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_remove_resumeschema_passingyear_resumeschema_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumeschema',
            old_name='year',
            new_name='passingyear',
        ),
    ]
