# Generated by Django 4.1.1 on 2023-03-23 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_resumeschema_hssname_resumeschema_hssyear_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeschema',
            name='hssmarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resumeschema',
            name='tenthmarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
